library(outliers)
library(EnvStats)

setwd("C:/Users/Tyler.Harman/Desktop/cellcount_work/cellcount_data/stat_code/")

RA<-read.csv("Regression_Analysis_IND.csv",header=T)

RA_F192<-subset(RA,Species=="F192")
RA_F192A<-subset(RA_F192,Concentration=="A")
RA_F192B<-subset(RA_F192,Concentration=="B")
RA_F192C<-subset(RA_F192,Concentration=="C")
RA_F192D<-subset(RA_F192,Concentration=="D")
RA_F192E<-subset(RA_F192,Concentration=="E")

rosnerTest(RA_F192A$Script)
rosnerTest(RA_F192B$Script)
rosnerTest(RA_F192C$Script)
rosnerTest(RA_F192D$Script)
rosnerTest(RA_F192E$Script)
rosnerTest(RA_F192A$Visual)
rosnerTest(RA_F192B$Visual)
rosnerTest(RA_F192C$Visual)
rosnerTest(RA_F192D$Visual)
rosnerTest(RA_F192E$Visual)


RA_F210<-subset(RA,Species=="F210")
RA_F210A<-subset(RA_F210,Concentration=="A")
RA_F210B<-subset(RA_F210,Concentration=="B")
RA_F210C<-subset(RA_F210,Concentration=="C")
RA_F210D<-subset(RA_F210,Concentration=="D")
RA_F210E<-subset(RA_F210,Concentration=="E")

rosnerTest(RA_F210A$Script)
rosnerTest(RA_F210B$Script)
rosnerTest(RA_F210C$Script)
rosnerTest(RA_F210D$Script)
rosnerTest(RA_F210E$Script)
rosnerTest(RA_F210A$Visual)
rosnerTest(RA_F210B$Visual)
rosnerTest(RA_F210C$Visual)
rosnerTest(RA_F210D$Visual)
rosnerTest(RA_F210E$Visual)


RA_Anabena<-subset(RA,Species=="Anabena")
RA_AnabenaHigh<-subset(RA_Anabena,Concentration=="High")
RA_AnabenaMed<-subset(RA_Anabena,Concentration=="Medium")
RA_AnabenaLow<-subset(RA_Anabena,Concentration=="Low")

rosnerTest(RA_AnabenaHigh$Script)
rosnerTest(RA_AnabenaMed$Script)
rosnerTest(RA_AnabenaLow$Script)
rosnerTest(RA_AnabenaHigh$Visual)
rosnerTest(RA_AnabenaMed$Visual)
rosnerTest(RA_AnabenaLow$Visual)


RA_Shewanella<-subset(RA,Species=="Shewanella")
RA_ShewanellaA<-subset(RA_Shewanella,Concentration=="A")
RA_ShewanellaB<-subset(RA_Shewanella,Concentration=="B")
RA_ShewanellaC<-subset(RA_Shewanella,Concentration=="C")
RA_ShewanellaD<-subset(RA_Shewanella,Concentration=="D")
RA_ShewanellaE<-subset(RA_Shewanella,Concentration=="E")

rosnerTest(RA_ShewanellaA$Script)
rosnerTest(RA_ShewanellaB$Script)
rosnerTest(RA_ShewanellaC$Script)
rosnerTest(RA_ShewanellaD$Script)
rosnerTest(RA_ShewanellaE$Script)
rosnerTest(RA_ShewanellaA$Visual)
rosnerTest(RA_ShewanellaB$Visual)
rosnerTest(RA_ShewanellaC$Visual)
rosnerTest(RA_ShewanellaD$Visual)
rosnerTest(RA_ShewanellaE$Visual)
